# Generated by Django 3.1.6 on 2021-02-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondata',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
